/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardStorageRouteImport } from './routes/_authenticated/dashboard/storage'
import { Route as AuthenticatedDashboardBotsIndexRouteImport } from './routes/_authenticated/dashboard/bots/index'
import { Route as AuthenticatedDashboardBotsIdRouteImport } from './routes/_authenticated/dashboard/bots/$id'
import { Route as ApiPublicCleanupDeliveriesRouteImport } from './routes/api/public/cleanup/deliveries'
import { Route as AuthenticatedDashboardBotsIdIndexRouteImport } from './routes/_authenticated/dashboard/bots/$id/index'
import { Route as AuthenticatedDashboardBotsIdDeploymentsRouteImport } from './routes/_authenticated/dashboard/bots/$id/deployments'
import { Route as AuthenticatedDashboardBotsIdLogsRouteImport } from './routes/_authenticated/dashboard/bots/$id/logs'
import { Route as AuthenticatedDashboardBotsIdSettingsRouteImport } from './routes/_authenticated/dashboard/bots/$id/settings'
import { Route as AuthenticatedDashboardBotsIdStorageRouteImport } from './routes/_authenticated/dashboard/bots/$id/storage'
import { Route as AuthenticatedDashboardBotsNewIndexRouteImport } from './routes/_authenticated/dashboard/bots/new/index'
import { Route as AuthenticatedDashboardBotsNewUploadRouteImport } from './routes/_authenticated/dashboard/bots/new/upload'
import { Route as ApiPublicTelegramWebhookBotIdRouteImport } from './routes/api/public/telegram/webhook.$botId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStorageRoute =
  AuthenticatedDashboardStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBotsIndexRoute =
  AuthenticatedDashboardBotsIndexRouteImport.update({
    id: '/bots/',
    path: '/bots/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBotsIdRoute =
  AuthenticatedDashboardBotsIdRouteImport.update({
    id: '/bots/$id',
    path: '/bots/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicCleanupDeliveriesRoute =
  ApiPublicCleanupDeliveriesRouteImport.update({
    id: '/api/public/cleanup/deliveries',
    path: '/api/public/cleanup/deliveries',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardBotsIdIndexRoute =
  AuthenticatedDashboardBotsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardBotsIdRoute,
  } as any)
const AuthenticatedDashboardBotsIdDeploymentsRoute =
  AuthenticatedDashboardBotsIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthenticatedDashboardBotsIdRoute,
  } as any)
const AuthenticatedDashboardBotsIdLogsRoute =
  AuthenticatedDashboardBotsIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedDashboardBotsIdRoute,
  } as any)
const AuthenticatedDashboardBotsIdSettingsRoute =
  AuthenticatedDashboardBotsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardBotsIdRoute,
  } as any)
const AuthenticatedDashboardBotsIdStorageRoute =
  AuthenticatedDashboardBotsIdStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedDashboardBotsIdRoute,
  } as any)
const AuthenticatedDashboardBotsNewIndexRoute =
  AuthenticatedDashboardBotsNewIndexRouteImport.update({
    id: '/bots/new/',
    path: '/bots/new/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBotsNewUploadRoute =
  AuthenticatedDashboardBotsNewUploadRouteImport.update({
    id: '/bots/new/upload',
    path: '/bots/new/upload',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicTelegramWebhookBotIdRoute =
  ApiPublicTelegramWebhookBotIdRouteImport.update({
    id: '/api/public/telegram/webhook/$botId',
    path: '/api/public/telegram/webhook/$botId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/storage': typeof AuthenticatedDashboardStorageRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/bots/$id': typeof AuthenticatedDashboardBotsIdRouteWithChildren
  '/api/public/cleanup/deliveries': typeof ApiPublicCleanupDeliveriesRoute
  '/dashboard/bots/': typeof AuthenticatedDashboardBotsIndexRoute
  '/dashboard/bots/$id/deployments': typeof AuthenticatedDashboardBotsIdDeploymentsRoute
  '/dashboard/bots/$id/logs': typeof AuthenticatedDashboardBotsIdLogsRoute
  '/dashboard/bots/$id/settings': typeof AuthenticatedDashboardBotsIdSettingsRoute
  '/dashboard/bots/$id/storage': typeof AuthenticatedDashboardBotsIdStorageRoute
  '/dashboard/bots/new/upload': typeof AuthenticatedDashboardBotsNewUploadRoute
  '/api/public/telegram/webhook/$botId': typeof ApiPublicTelegramWebhookBotIdRoute
  '/dashboard/bots/$id/': typeof AuthenticatedDashboardBotsIdIndexRoute
  '/dashboard/bots/new/': typeof AuthenticatedDashboardBotsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/storage': typeof AuthenticatedDashboardStorageRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/cleanup/deliveries': typeof ApiPublicCleanupDeliveriesRoute
  '/dashboard/bots': typeof AuthenticatedDashboardBotsIndexRoute
  '/dashboard/bots/$id/deployments': typeof AuthenticatedDashboardBotsIdDeploymentsRoute
  '/dashboard/bots/$id/logs': typeof AuthenticatedDashboardBotsIdLogsRoute
  '/dashboard/bots/$id/settings': typeof AuthenticatedDashboardBotsIdSettingsRoute
  '/dashboard/bots/$id/storage': typeof AuthenticatedDashboardBotsIdStorageRoute
  '/dashboard/bots/new/upload': typeof AuthenticatedDashboardBotsNewUploadRoute
  '/api/public/telegram/webhook/$botId': typeof ApiPublicTelegramWebhookBotIdRoute
  '/dashboard/bots/$id': typeof AuthenticatedDashboardBotsIdIndexRoute
  '/dashboard/bots/new': typeof AuthenticatedDashboardBotsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/storage': typeof AuthenticatedDashboardStorageRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/bots/$id': typeof AuthenticatedDashboardBotsIdRouteWithChildren
  '/api/public/cleanup/deliveries': typeof ApiPublicCleanupDeliveriesRoute
  '/_authenticated/dashboard/bots/': typeof AuthenticatedDashboardBotsIndexRoute
  '/_authenticated/dashboard/bots/$id/deployments': typeof AuthenticatedDashboardBotsIdDeploymentsRoute
  '/_authenticated/dashboard/bots/$id/logs': typeof AuthenticatedDashboardBotsIdLogsRoute
  '/_authenticated/dashboard/bots/$id/settings': typeof AuthenticatedDashboardBotsIdSettingsRoute
  '/_authenticated/dashboard/bots/$id/storage': typeof AuthenticatedDashboardBotsIdStorageRoute
  '/_authenticated/dashboard/bots/new/upload': typeof AuthenticatedDashboardBotsNewUploadRoute
  '/api/public/telegram/webhook/$botId': typeof ApiPublicTelegramWebhookBotIdRoute
  '/_authenticated/dashboard/bots/$id/': typeof AuthenticatedDashboardBotsIdIndexRoute
  '/_authenticated/dashboard/bots/new/': typeof AuthenticatedDashboardBotsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/'
    | '/dashboard/bots/$id'
    | '/api/public/cleanup/deliveries'
    | '/dashboard/bots/'
    | '/dashboard/bots/$id/deployments'
    | '/dashboard/bots/$id/logs'
    | '/dashboard/bots/$id/settings'
    | '/dashboard/bots/$id/storage'
    | '/dashboard/bots/new/upload'
    | '/api/public/telegram/webhook/$botId'
    | '/dashboard/bots/$id/'
    | '/dashboard/bots/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard'
    | '/api/public/cleanup/deliveries'
    | '/dashboard/bots'
    | '/dashboard/bots/$id/deployments'
    | '/dashboard/bots/$id/logs'
    | '/dashboard/bots/$id/settings'
    | '/dashboard/bots/$id/storage'
    | '/dashboard/bots/new/upload'
    | '/api/public/telegram/webhook/$botId'
    | '/dashboard/bots/$id'
    | '/dashboard/bots/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/storage'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/bots/$id'
    | '/api/public/cleanup/deliveries'
    | '/_authenticated/dashboard/bots/'
    | '/_authenticated/dashboard/bots/$id/deployments'
    | '/_authenticated/dashboard/bots/$id/logs'
    | '/_authenticated/dashboard/bots/$id/settings'
    | '/_authenticated/dashboard/bots/$id/storage'
    | '/_authenticated/dashboard/bots/new/upload'
    | '/api/public/telegram/webhook/$botId'
    | '/_authenticated/dashboard/bots/$id/'
    | '/_authenticated/dashboard/bots/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicCleanupDeliveriesRoute: typeof ApiPublicCleanupDeliveriesRoute
  ApiPublicTelegramWebhookBotIdRoute: typeof ApiPublicTelegramWebhookBotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/storage': {
      id: '/_authenticated/dashboard/storage'
      path: '/storage'
      fullPath: '/dashboard/storage'
      preLoaderRoute: typeof AuthenticatedDashboardStorageRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bots/': {
      id: '/_authenticated/dashboard/bots/'
      path: '/bots'
      fullPath: '/dashboard/bots/'
      preLoaderRoute: typeof AuthenticatedDashboardBotsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bots/$id': {
      id: '/_authenticated/dashboard/bots/$id'
      path: '/bots/$id'
      fullPath: '/dashboard/bots/$id'
      preLoaderRoute: typeof AuthenticatedDashboardBotsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/cleanup/deliveries': {
      id: '/api/public/cleanup/deliveries'
      path: '/api/public/cleanup/deliveries'
      fullPath: '/api/public/cleanup/deliveries'
      preLoaderRoute: typeof ApiPublicCleanupDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/bots/$id/': {
      id: '/_authenticated/dashboard/bots/$id/'
      path: '/'
      fullPath: '/dashboard/bots/$id/'
      preLoaderRoute: typeof AuthenticatedDashboardBotsIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardBotsIdRoute
    }
    '/_authenticated/dashboard/bots/$id/deployments': {
      id: '/_authenticated/dashboard/bots/$id/deployments'
      path: '/deployments'
      fullPath: '/dashboard/bots/$id/deployments'
      preLoaderRoute: typeof AuthenticatedDashboardBotsIdDeploymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardBotsIdRoute
    }
    '/_authenticated/dashboard/bots/$id/logs': {
      id: '/_authenticated/dashboard/bots/$id/logs'
      path: '/logs'
      fullPath: '/dashboard/bots/$id/logs'
      preLoaderRoute: typeof AuthenticatedDashboardBotsIdLogsRouteImport
      parentRoute: typeof AuthenticatedDashboardBotsIdRoute
    }
    '/_authenticated/dashboard/bots/$id/settings': {
      id: '/_authenticated/dashboard/bots/$id/settings'
      path: '/settings'
      fullPath: '/dashboard/bots/$id/settings'
      preLoaderRoute: typeof AuthenticatedDashboardBotsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardBotsIdRoute
    }
    '/_authenticated/dashboard/bots/$id/storage': {
      id: '/_authenticated/dashboard/bots/$id/storage'
      path: '/storage'
      fullPath: '/dashboard/bots/$id/storage'
      preLoaderRoute: typeof AuthenticatedDashboardBotsIdStorageRouteImport
      parentRoute: typeof AuthenticatedDashboardBotsIdRoute
    }
    '/_authenticated/dashboard/bots/new/': {
      id: '/_authenticated/dashboard/bots/new/'
      path: '/bots/new'
      fullPath: '/dashboard/bots/new/'
      preLoaderRoute: typeof AuthenticatedDashboardBotsNewIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bots/new/upload': {
      id: '/_authenticated/dashboard/bots/new/upload'
      path: '/bots/new/upload'
      fullPath: '/dashboard/bots/new/upload'
      preLoaderRoute: typeof AuthenticatedDashboardBotsNewUploadRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/telegram/webhook/$botId': {
      id: '/api/public/telegram/webhook/$botId'
      path: '/api/public/telegram/webhook/$botId'
      fullPath: '/api/public/telegram/webhook/$botId'
      preLoaderRoute: typeof ApiPublicTelegramWebhookBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardBotsIdRouteChildren {
  AuthenticatedDashboardBotsIdDeploymentsRoute: typeof AuthenticatedDashboardBotsIdDeploymentsRoute
  AuthenticatedDashboardBotsIdLogsRoute: typeof AuthenticatedDashboardBotsIdLogsRoute
  AuthenticatedDashboardBotsIdSettingsRoute: typeof AuthenticatedDashboardBotsIdSettingsRoute
  AuthenticatedDashboardBotsIdStorageRoute: typeof AuthenticatedDashboardBotsIdStorageRoute
  AuthenticatedDashboardBotsIdIndexRoute: typeof AuthenticatedDashboardBotsIdIndexRoute
}

const AuthenticatedDashboardBotsIdRouteChildren: AuthenticatedDashboardBotsIdRouteChildren =
  {
    AuthenticatedDashboardBotsIdDeploymentsRoute:
      AuthenticatedDashboardBotsIdDeploymentsRoute,
    AuthenticatedDashboardBotsIdLogsRoute:
      AuthenticatedDashboardBotsIdLogsRoute,
    AuthenticatedDashboardBotsIdSettingsRoute:
      AuthenticatedDashboardBotsIdSettingsRoute,
    AuthenticatedDashboardBotsIdStorageRoute:
      AuthenticatedDashboardBotsIdStorageRoute,
    AuthenticatedDashboardBotsIdIndexRoute:
      AuthenticatedDashboardBotsIdIndexRoute,
  }

const AuthenticatedDashboardBotsIdRouteWithChildren =
  AuthenticatedDashboardBotsIdRoute._addFileChildren(
    AuthenticatedDashboardBotsIdRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardStorageRoute: typeof AuthenticatedDashboardStorageRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardBotsIdRoute: typeof AuthenticatedDashboardBotsIdRouteWithChildren
  AuthenticatedDashboardBotsIndexRoute: typeof AuthenticatedDashboardBotsIndexRoute
  AuthenticatedDashboardBotsNewUploadRoute: typeof AuthenticatedDashboardBotsNewUploadRoute
  AuthenticatedDashboardBotsNewIndexRoute: typeof AuthenticatedDashboardBotsNewIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardStorageRoute: AuthenticatedDashboardStorageRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardBotsIdRoute:
      AuthenticatedDashboardBotsIdRouteWithChildren,
    AuthenticatedDashboardBotsIndexRoute: AuthenticatedDashboardBotsIndexRoute,
    AuthenticatedDashboardBotsNewUploadRoute:
      AuthenticatedDashboardBotsNewUploadRoute,
    AuthenticatedDashboardBotsNewIndexRoute:
      AuthenticatedDashboardBotsNewIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicCleanupDeliveriesRoute: ApiPublicCleanupDeliveriesRoute,
  ApiPublicTelegramWebhookBotIdRoute: ApiPublicTelegramWebhookBotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
